name: testJavascriptActions

on:
  push:

jobs:
  successful:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/jsaction
        id: jsaction
        with:
          someinput: >-
            some input
            will be some input.
      - run: |
          echo ${{ steps.jsaction.outputs.anotheroutput }}
          echo "IS_SUCCESS=DEFINATELY" >> $GITHUB_ENV
  failing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/jsaction
        id: jsaction
        with:
          someinput: 'some input'
      - run: |
          echo ${{ steps.jsaction.outputs.anotheroutput }}
          echo "IS_SUCCESS=DEFINATELY" >> $GITHUB_ENV
          exit 1
